import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ProjectSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

let header = (
  <header>
    <Link href={'/'} legacyBehavior>
      <div className="absolute" style={{ top: "-44px", left: "80px" }}>
        <Image src="/logo.png" alt="Site logo" width={140} height={140} priority={true} />
      </div>
    </Link>
  </header>
)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {header}
        {children}
      </body>
    </html>
  );
}
